# GitHub Dependabot configuration for sbtm-tool
# Session-Based Test Management Tool with NiceGUI

version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "adamkwhite"
    assignees:
      - "adamkwhite"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "nicegui"
      - "python"
    # Group NiceGUI and web dependencies
    groups:
      nicegui-ecosystem:
        patterns:
          - "nicegui*"
          - "fastapi*"
          - "starlette*"
          - "uvicorn*"
        update-types:
          - "minor"
          - "patch"
      database-dependencies:
        patterns:
          - "sqlalchemy*"
          - "alembic*"
          - "psycopg2*"
        update-types:
          - "minor"
          - "patch"
    allow:
      - dependency-type: "all"
    ignore:
      # Be careful with major updates for critical packages
      - dependency-name: "nicegui"
        update-types: ["version-update:semver-major"]
      - dependency-name: "sqlalchemy"
        update-types: ["version-update:semver-major"]