version: '3.8'

services:
  sbtm-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://sbtm:sbtm123@db:5432/sbtm
      - ENVIRONMENT=production
    depends_on:
      - db
    volumes:
      - app_data:/app/data
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=sbtm
      - POSTGRES_USER=sbtm
      - POSTGRES_PASSWORD=sbtm123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
  app_data: